// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:9e48f4fc-c035-4edb-b225-0ee43ae9f24b",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ym6GFjpvy",
    "aws_user_pools_web_client_id": "2j1ggohtjqlhvm8c3vrrr1m75d",
    "oauth": {},
    "aws_user_files_s3_bucket": "amplify-team-s3teamdev-teamdev",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://m3cdiyh6u5ftjfziqisexba6hq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
